Repository AY2425S2-CS2103T-T15-3/tp, pull requests merged in 2025-04, with the labels that each got.

#77 Update UI class diagram
  docs/UserGuide.md
  docs/diagrams/UiClassDiagram.puml
Labels: priority.High

#85 Update UG for addtags & removetags
  docs/UserGuide.md
Labels: priority.High

#88 Fix issue with automatic conversion of invalid dates in leave command
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/leave/Leave.java
  src/test/java/seedu/address/model/leave/LeaveTest.java
Labels: alpha-bug

#95 Fix duplicate NRIC issue
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: alpha-bug

#107 Allow case-insensitivity of nric in attendance command
  src/main/java/seedu/address/logic/commands/AttendanceCommand.java
Labels: alpha-bug

#106 Update title of ui main window
  src/main/resources/view/MainWindow.fxml
Labels: alpha-bug

#93 Update HelpWindow url
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: alpha-bug

#104 Add more details and specifications to our available commands on UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AttendanceCommand.java
Labels: priority.High

#108 Fix tag error messages, update user guide for tags, and update empty state of UI
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/RemoveTagCommand.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemoveTagCommandParser.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/ui/PersonDetailsPanel.java
  src/main/resources/view/PersonDetailsPanel.fxml
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/TagTest.java
Labels: priority.High, alpha-bug

#114 Branch alphatestv2.0
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/RemoveTagCommand.java
Labels: alpha-bug

#120 Update help message screenshot
  docs/images/helpMessage.png
Labels: alpha-bug

#117 Update developer guide links, project name and badges
  README.md
  docs/DeveloperGuide.md
  docs/index.md
Labels: alpha-bug

#181 Functionality bugfixing - Tag character count, attendance term, scrollbar for results
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/ui/PersonDetailsPanel.java
  src/main/resources/view/LightTheme.css
  src/main/resources/view/ResultDisplay.fxml
Labels: priority.High, severity.High

#185 Fix bugs related to Leave
  src/main/java/seedu/address/logic/parser/LeaveCommandParser.java
  src/main/java/seedu/address/model/leave/Leave.java
Labels: type.Bug

#186 Branch v1.6
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/model/leave/Leave.java
  src/main/java/seedu/address/model/person/Hire.java
Labels: priority.High

#187 Add a way to refresh UI
  src/main/java/seedu/address/ui/PersonDetailsPanel.java
Labels: priority.High

#189 Update use cases in DG
  docs/DeveloperGuide.md
  src/main/java/seedu/address/model/leave/Leave.java
Labels: priority.High

#188 Fix UI panel behavior for attendance/clear/delete commands
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug

#190 Improve error message on delete and view command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/model/leave/Leave.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
Labels: priority.High

#191 Edit target user profile in DG
  docs/DeveloperGuide.md
Labels: priority.High
